In [1]:
import numpy as np

# mathematical operation performed on array and matrix

In [9]:
x1=np.arange(1,10).reshape(3,3)
print(arr3)
x2=np.arange(1,10).reshape(3,3)
print(x2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
x1+x2


array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [14]:
np.add(x1,x2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [15]:
x1/x2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.divide(x1,x2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# multiply in form of matrix product

In [20]:
x1 @ x2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [22]:
x1.max()

9

In [23]:
x1.argmax()

8

axis =0 is define columns datasets and axis = 1 is define rows datasets

In [26]:
x1.max(axis=0)

array([7, 8, 9])

In [27]:
x1.max(axis=1)

array([3, 6, 9])

In [28]:
x1.sum()

45

In [29]:
x1.sum(axis=0)

array([12, 15, 18])

In [30]:
np.mean(x1)

5.0

In [31]:
np.std(x1)

2.581988897471611

In [32]:
np.sqrt(x1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [33]:
np.exp(x1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [34]:
np.log(x1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [35]:
np.log10(x1)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])

# python numpy array slicing(:)

In [40]:
mx=np.arange(1,51).reshape(5,10)
print(mx)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]
 [31 32 33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48 49 50]]


In [48]:
mx[0,0]
mx[4,4]

45

In [49]:
mx[:,0]

array([ 1, 11, 21, 31, 41])

In [51]:
mx[:,:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [52]:
mx[:]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [53]:
mx.itemsize

4

In [55]:
mx.dtype

dtype('int32')

In [56]:
32/8

4.0

In [58]:
mx[1:3,1:3]

array([[12, 13],
       [22, 23]])

In [60]:
mx[:,0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33],
       [41, 42, 43]])

In [61]:
mx[:,1:2]

array([[ 2],
       [12],
       [22],
       [32],
       [42]])