# Numpylib


In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.size

3

In [5]:
arr.shape

(3,)

In [6]:
arr.ndim

1

In [7]:
arr.dtype

dtype('int32')

In [12]:
arr3=np.array([[[1,2,3],
       [4,5,6],
       [7,8,9],
        [10,11,12],
      [13,14,15],
      [16,17,18]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]]]


In [13]:
type(arr3)

numpy.ndarray

In [14]:
arr3.ndim

3

In [15]:
arr3.size

18

In [16]:
arr3.dtype

dtype('int32')

In [17]:
arr3.shape

(1, 6, 3)

# matrix


In [20]:
mx=np.ones((1,5))
print(mx)

[[1. 1. 1. 1. 1.]]


In [22]:
mx=np.ones((2,3),dtype=int)
print(mx)

[[1 1 1]
 [1 1 1]]


In [24]:
mx=np.zeros((2,3))
print(mx)

[[0. 0. 0.]
 [0. 0. 0.]]


In [26]:
mx=np.ones((2,3),dtype=bool)
print(mx)

[[ True  True  True]
 [ True  True  True]]
