# Numpy function call

In [1]:
import numpy as np

# arange()

In [2]:
#np.arange(start,end,steps)
arr0=np.arange(1,11)
print(arr0)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


# reshape()

In [4]:
arr2=arr0.reshape(2,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# transpose()

In [5]:
arr2.transpose()


array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

# ravel() and flatten()

In [6]:
arr2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr2.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# linspace()

In [20]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# practice

In [10]:
x=np.array([1,2,3,4])
print(x)

[1 2 3 4]


In [11]:
x1=x.reshape(2,2)
print(x1)

[[1 2]
 [3 4]]


In [12]:
x1.transpose()

array([[1, 3],
       [2, 4]])

In [13]:
x1.ravel()

array([1, 2, 3, 4])

In [14]:
x1.flatten()

array([1, 2, 3, 4])

In [18]:
np.linspace(1,4,3)

array([1. , 2.5, 4. ])