# Random Sampling with Numpy 

In [1]:
import numpy as np
import random 

In [2]:
#random is used for generating random data and  performed different operation on these data
# rand class
np.random.rand((3))

array([0.41494138, 0.29928024, 0.7642905 ])

In [6]:
np.random.rand(3,3)

array([[0.11096738, 0.26282515, 0.13109284],
       [0.54509337, 0.76586126, 0.61566962],
       [0.366852  , 0.32830177, 0.0449311 ]])

In [7]:
# randint class is used to create integer data
np.random.randint(1,4,(4,4))

array([[3, 3, 1, 1],
       [3, 1, 3, 3],
       [2, 2, 1, 2],
       [3, 2, 1, 2]])

In [14]:
np.random.randint(1,4,(4,4,3))

array([[[3, 2, 3],
        [2, 2, 3],
        [2, 3, 2],
        [3, 3, 3]],

       [[1, 2, 2],
        [1, 2, 2],
        [2, 2, 2],
        [3, 2, 3]],

       [[1, 2, 3],
        [3, 3, 1],
        [2, 2, 2],
        [1, 1, 3]],

       [[1, 2, 3],
        [2, 3, 2],
        [1, 1, 2],
        [3, 2, 1]]])

In [19]:
#used permutation class
x=[1,2,3,4]
np.random.permutation(x)


array([2, 4, 3, 1])

In [20]:
x=[1,2,3,4]
np.random.permutation(x)

array([2, 3, 1, 4])

In [21]:
x=[1,2,3,4]
np.random.permutation(x)

array([2, 1, 3, 4])

In [23]:
#used choice() method for generating random data like OTP
for i in range(20):
    print(np.random.choice(x))

4
3
3
2
1
1
3
2
4
3
2
2
2
4
2
3
2
1
3
3
