In [ ]:
import numpy as np

# array concatenate and spliting

In [ ]:
arr4=np.arange(1,17).reshape(4,4)
print(arr4)

In [ ]:
arr41=np.arange(17,33).reshape(4,4)
print(arr41)

In [5]:
np.concatenate((arr4,arr41))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [6]:
#another method for vertical concatenate
np.vstack((arr4,arr41))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [7]:
# horizontal concatenate
np.hstack((arr4,arr41))

array([[ 1,  2,  3,  4, 17, 18, 19, 20],
       [ 5,  6,  7,  8, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28],
       [13, 14, 15, 16, 29, 30, 31, 32]])

In [8]:
np.hstack((arr4,arr41,arr4))

array([[ 1,  2,  3,  4, 17, 18, 19, 20,  1,  2,  3,  4],
       [ 5,  6,  7,  8, 21, 22, 23, 24,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 25, 26, 27, 28,  9, 10, 11, 12],
       [13, 14, 15, 16, 29, 30, 31, 32, 13, 14, 15, 16]])

# split () method

In [10]:
np.split(arr4,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]), array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [11]:
np.split(arr41,[1,3])

[array([[17, 18, 19, 20]]), array([[21, 22, 23, 24],
        [25, 26, 27, 28]]), array([[29, 30, 31, 32]])]